{% set name = "beanquery" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}  # This constraint induced by tatsu

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beanquery-{{ version }}.tar.gz
  sha256: b69e099b8421b219bbcc3293af77e3c4ccad7ab25bf520fee48788672ffbf64a
  patches:
    - requirements.patch

build:
  entry_points:
    - bean-query = beanquery.shell:main
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - beancount >=2.3.4
    - click >7.0
    - python-dateutil >=2.6.0
    - tatsu >=5.7.4

test:
  imports:
    - beanquery
  commands:
    - pip check
    - bean-query --help
    # - pytest --pyargs beanquery -- re-enable once off staged-recipes; tests fail on Windows (but we're noarch: python)
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  summary: SQL-like query tool for the Beancount accounting software
  home: https://github.com/beancount/beanquery
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
